### PR TITLE
Html css

### PR DESCRIPTION
**Pull request by daudi13**
#In this project I:

-Added a .html file with the text "Hello Microverse"
-Added a .css file that changes the text to a color of my liking
-Added a .gitignore
-Added each file on a unique commit
-Added a README.md file with a description of the project
-Used Github flow
-Created a new branch
-Created a test.md file and added it to .gitignore, along with the node_modules folder
-Set up linters

### CODE REVIEW

**Comment by daudi13** [comment]
I made the necessary changes to my code but with a cost of having to pull another pull request. I know it is something I'm not supposed to be doing and there are policies at Microverse regarding it,  but I earlier didn't understand why my code wasn't working and I felt the need to start over again so I sought the help of a peer and they explained everything to me. This will NOT happen again.

**Comment by julie-ify** [comment]
Hi @daudi13

I saw that you were asking how to continue working on the same pull request. To continue working on the same pull request all you just have to do is to make the required changes by the code reviewer and push to Github. Then go to the same pull request and see the changes you just pushed and copy the same pull request link and submit for another review. Hope this helps. 

You can always reach a code reviewer on slack if they do not respond to your questions here as they might not receive notification about your messages 😉

**Review by julie-ify — APPROVED** [review]
## Hi @daudi13, 

# Highlights
- Good job implementing the required changes from the previous reviewer ✔️ 

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Approved emoji

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by daudi13** [comment]
Thank you @julie-ify

**Pull request merged**
